/**
 * PCB editor toolbar layouts, transcribed from KiCad pcbnew's
 * `toolbars_pcb_editor.cpp` (PCB_EDIT_TOOLBAR_SETTINGS::DefaultToolbarConfig,
 * TOOLBAR_LOC::LEFT / RIGHT / TOP_MAIN). Separators mirror AppendSeparator;
 * KiCad's AppendGroup members are listed consecutively as radio buttons, the
 * same convention the schematic toolbars.ts uses.
 */

import type { ToolEntry } from '../../ui/Toolbar.js';

const sep: ToolEntry = 'sep';

/** TOP_MAIN toolbar. */
export const PCB_TOP_TOOLBAR: ToolEntry[] = [
  { id: 'new', icon: 'new', title: 'New board' },
  { id: 'open', icon: 'open', title: 'Open' },
  { id: 'save', icon: 'save', title: 'Save' },
  sep,
  { id: 'boardSetup', icon: 'boardSetup', title: 'Board setup' },
  sep,
  { id: 'pageSettings', icon: 'pageSettings', title: 'Page settings' },
  { id: 'print', icon: 'print', title: 'Print' },
  { id: 'plot', icon: 'plot', title: 'Plot' },
  sep,
  { id: 'undo', icon: 'undo', title: 'Undo' },
  { id: 'redo', icon: 'redo', title: 'Redo' },
  sep,
  { id: 'find', icon: 'find', title: 'Find' },
  sep,
  { id: 'zoomRedraw', icon: 'zoomRedraw', title: 'Redraw view' },
  { id: 'zoomIn', icon: 'zoomIn', title: 'Zoom in' },
  { id: 'zoomOut', icon: 'zoomOut', title: 'Zoom out' },
  { id: 'zoomFit', icon: 'zoomFit', title: 'Zoom to fit board' },
  { id: 'zoomFitObjects', icon: 'zoomFitObjects', title: 'Zoom to fit objects' },
  { id: 'zoomTool', icon: 'zoomTool', title: 'Zoom to selection' },
  sep,
  { id: 'rotateCCW', icon: 'rotateCCW', title: 'Rotate counterclockwise' },
  { id: 'rotateCW', icon: 'rotateCW', title: 'Rotate clockwise' },
  { id: 'mirrorV', icon: 'mirrorV', title: 'Mirror vertically' },
  { id: 'mirrorH', icon: 'mirrorH', title: 'Mirror horizontally' },
  { id: 'group', icon: 'group', title: 'Group items' },
  { id: 'ungroup', icon: 'ungroup', title: 'Ungroup items' },
  { id: 'lock', icon: 'lock', title: 'Lock' },
  { id: 'unlock', icon: 'unlock', title: 'Unlock' },
  sep,
  { id: 'footprintEditor', icon: 'footprintEditor', title: 'Footprint Editor' },
  { id: 'footprintBrowser', icon: 'footprintBrowser', title: 'Footprint Library Browser' },
  { id: 'threeDViewer', icon: 'threeDViewer', title: '3D Viewer' },
  sep,
  { id: 'updatePcbFromSch', icon: 'updatePcbFromSch', title: 'Update PCB from schematic' },
  { id: 'runDRC', icon: 'runDRC', title: 'Design Rules Checker' },
  sep,
  { id: 'showEeschema', icon: 'showEeschema', title: 'Open schematic in Schematic Editor' },
];

/** LEFT (view options) toolbar. */
export const PCB_LEFT_TOOLBAR: ToolEntry[] = [
  { id: 'toggleGrid', icon: 'toggleGrid', title: 'Show grid', toggle: true },
  {
    id: 'toggleGridOverrides',
    icon: 'toggleGridOverrides',
    title: 'Toggle grid overrides',
    toggle: true,
  },
  {
    id: 'togglePolarCoords',
    icon: 'togglePolarCoords',
    title: 'Display polar coordinates',
    toggle: true,
  },
  { id: 'unitsMm', icon: 'unitsMm', title: 'Units in millimetres', toggle: true },
  { id: 'unitsInches', icon: 'unitsInches', title: 'Units in inches', toggle: true },
  { id: 'unitsMils', icon: 'unitsMils', title: 'Units in mils', toggle: true },
  { id: 'crosshairSmall', icon: 'crosshairSmall', title: 'Small crosshairs', toggle: true },
  { id: 'crosshairFull', icon: 'crosshairFull', title: 'Full-window crosshairs', toggle: true },
  { id: 'crosshair45', icon: 'crosshair45', title: '45° crosshairs', toggle: true },
  sep,
  { id: 'lineModeFree', icon: 'lineModeFree', title: 'Line mode: free angle', toggle: true },
  { id: 'lineMode90', icon: 'lineMode90', title: 'Line mode: 90°', toggle: true },
  { id: 'lineMode45', icon: 'lineMode45', title: 'Line mode: 45°', toggle: true },
  sep,
  { id: 'showRatsnest', icon: 'showRatsnest', title: 'Show ratsnest', toggle: true },
  {
    id: 'ratsnestLineMode',
    icon: 'ratsnestLineMode',
    title: 'Curved ratsnest lines',
    toggle: true,
  },
  sep,
  { id: 'highContrast', icon: 'highContrast', title: 'High-contrast display mode', toggle: true },
  {
    id: 'toggleNetHighlight',
    icon: 'toggleNetHighlight',
    title: 'Toggle net highlighting',
    toggle: true,
  },
  sep,
  {
    id: 'zoneDisplayFilled',
    icon: 'zoneDisplayFilled',
    title: 'Show filled areas of zones',
    toggle: true,
  },
  {
    id: 'zoneDisplayOutline',
    icon: 'zoneDisplayOutline',
    title: 'Show only zone boundaries',
    toggle: true,
  },
  sep,
  { id: 'padDisplayMode', icon: 'padDisplayMode', title: 'Sketch pads', toggle: true },
  { id: 'viaDisplayMode', icon: 'viaDisplayMode', title: 'Sketch vias', toggle: true },
  { id: 'trackDisplayMode', icon: 'trackDisplayMode', title: 'Sketch tracks', toggle: true },
  sep,
  {
    id: 'showLayersManager',
    icon: 'showLayersManager',
    title: 'Show Appearance manager',
    toggle: true,
  },
  { id: 'showProperties', icon: 'showProperties', title: 'Show Properties panel', toggle: true },
];

/** RIGHT (tools) toolbar. */
export const PCB_RIGHT_TOOLBAR: ToolEntry[] = [
  { id: 'select', icon: 'select', title: 'Select items' },
  { id: 'selectLasso', icon: 'selectLasso', title: 'Select with lasso' },
  { id: 'localRatsnest', icon: 'localRatsnest', title: 'Show local ratsnest' },
  sep,
  { id: 'placeFootprint', icon: 'placeFootprint', title: 'Place footprints' },
  { id: 'routeTrack', icon: 'routeTrack', title: 'Route tracks' },
  { id: 'routeDiffPair', icon: 'routeDiffPair', title: 'Route differential pairs' },
  { id: 'tuneLength', icon: 'tuneLength', title: 'Tune length of a single track' },
  { id: 'tuneDiffPair', icon: 'tuneDiffPair', title: 'Tune length of a differential pair' },
  { id: 'tuneSkew', icon: 'tuneSkew', title: 'Tune skew of a differential pair' },
  { id: 'drawVia', icon: 'drawVia', title: 'Place vias' },
  { id: 'drawZone', icon: 'drawZone', title: 'Draw filled zones' },
  { id: 'drawRuleArea', icon: 'drawRuleArea', title: 'Draw rule areas (keepouts)' },
  sep,
  { id: 'drawLine', icon: 'drawLine', title: 'Draw lines' },
  { id: 'drawArc', icon: 'drawArc', title: 'Draw arcs' },
  { id: 'drawRectangle', icon: 'drawRectangle', title: 'Draw rectangles' },
  { id: 'drawCircle', icon: 'drawCircle', title: 'Draw circles' },
  { id: 'drawPolygon', icon: 'drawPolygon', title: 'Draw graphic polygons' },
  { id: 'drawBezier', icon: 'drawBezier', title: 'Draw beziers' },
  { id: 'placeImage', icon: 'placeImage', title: 'Place reference images' },
  { id: 'placeText', icon: 'placeText', title: 'Add text' },
  { id: 'drawTextBox', icon: 'drawTextBox', title: 'Add text boxes' },
  { id: 'drawTable', icon: 'drawTable', title: 'Add tables' },
  { id: 'dimAligned', icon: 'dimAligned', title: 'Add aligned dimensions' },
  { id: 'dimOrthogonal', icon: 'dimOrthogonal', title: 'Add orthogonal dimensions' },
  { id: 'dimCenter', icon: 'dimCenter', title: 'Add center dimensions' },
  { id: 'dimRadial', icon: 'dimRadial', title: 'Add radial dimensions' },
  { id: 'dimLeader', icon: 'dimLeader', title: 'Add leaders' },
  { id: 'deleteTool', icon: 'deleteTool', title: 'Interactive delete tool' },
  sep,
  { id: 'drillOrigin', icon: 'drillOrigin', title: 'Place the drill/place file origin' },
  { id: 'gridOrigin', icon: 'gridOrigin', title: 'Set the grid origin point' },
  { id: 'placePoint', icon: 'placePoint', title: 'Place points' },
  { id: 'measure', icon: 'measure', title: 'Measure distance' },
];

/**
 * Selection Filter categories (pcbnew panel_selection_filter_base),
 * two columns row-major like the panel.
 */
export const PCB_FILTER_CATS: [string, string][] = [
  ['lockedItems', 'Locked items'],
  ['footprints', 'Footprints'],
  ['text', 'Text'],
  ['tracks', 'Tracks'],
  ['vias', 'Vias'],
  ['zones', 'Zones'],
  ['pads', 'Pads'],
  ['graphics', 'Graphics'],
  ['keepouts', 'Rule Areas'],
  ['dimensions', 'Dimensions'],
  ['otherItems', 'Other items'],
  ['points', 'Points'],
];
