/**
 * Maps each toolbar tool id to KiCad's own icon (the dark-theme SVGs vendored
 * under assets/toolbar). Bitmap names are taken from KiCad's SCH_ACTIONS /
 * ACTIONS `.Icon(BITMAPS::…)` definitions. GPL like this project.
 */
const URLS = import.meta.glob('../assets/toolbar/*.svg', {
  query: '?url',
  import: 'default',
  eager: true,
}) as Record<string, string>;

const BITMAP: Record<string, string> = {
  showPcbNew: 'icon_pcbnew_24',
  // pcb editor (icons per PCB_ACTIONS/ACTIONS .Icon() in pcb_actions.cpp)
  boardSetup: 'options_board',
  threeDViewer: 'three_d',
  updatePcbFromSch: 'update_pcb_from_sch',
  runDRC: 'drc',
  showEeschema: 'icon_eeschema_24',
  lock: 'locked',
  unlock: 'lock_unlock',
  footprintBrowser: 'library_browser',
  togglePolarCoords: 'polar_coord',
  crosshair45: 'cursor_fullscreen45',
  showRatsnest: 'general_ratsnest',
  ratsnestLineMode: 'curved_ratsnest',
  highContrast: 'contrast_mode',
  toggleNetHighlight: 'net_highlight',
  zoneDisplayFilled: 'show_zone',
  zoneDisplayOutline: 'show_zone_disable',
  padDisplayMode: 'pad_sketch',
  viaDisplayMode: 'via_sketch',
  trackDisplayMode: 'showtrack',
  showLayersManager: 'layers_manager',
  selectLasso: 'lasso',
  localRatsnest: 'tool_ratsnest',
  placeFootprint: 'module',
  routeTrack: 'add_tracks',
  routeDiffPair: 'ps_diff_pair',
  tuneLength: 'ps_tune_length',
  tuneDiffPair: 'ps_diff_pair_tune_length',
  tuneSkew: 'ps_diff_pair_tune_phase',
  drawVia: 'add_via',
  drawZone: 'add_zone',
  drawRuleArea: 'add_keepout_area',
  drawLine: 'add_graphical_segments',
  drawArc: 'add_arc',
  drawRectangle: 'add_rectangle',
  drawCircle: 'add_circle',
  drawPolygon: 'add_graphical_polygon',
  drawBezier: 'add_bezier',
  placeImage: 'image',
  drawTextBox: 'add_textbox',
  drawTable: 'table',
  dimAligned: 'add_aligned_dimension',
  dimOrthogonal: 'add_orthogonal_dimension',
  dimCenter: 'add_center_dimension',
  dimRadial: 'add_radial_dimension',
  dimLeader: 'add_leader',
  deleteTool: 'trash',
  drillOrigin: 'set_origin',
  gridOrigin: 'grid_select_axis',
  placePoint: 'add_point',
  measure: 'measurement',
  // top toolbar
  new: 'new_generic',
  open: 'directory_open',
  save: 'save',
  schematicSetup: 'options_schematic',
  pageSettings: 'sheetset',
  print: 'print_button',
  plot: 'plot',
  paste: 'paste',
  undo: 'undo',
  redo: 'redo',
  find: 'find',
  findReplace: 'find_replace',
  zoomRedraw: 'refresh',
  zoomIn: 'zoom_in',
  zoomOut: 'zoom_out',
  zoomFit: 'zoom_fit_in_page',
  zoomFitObjects: 'zoom_fit_to_objects',
  zoomTool: 'zoom_area',
  navBack: 'left',
  navUp: 'up',
  navFwd: 'right',
  rotateCCW: 'rotate_ccw',
  rotateCW: 'rotate_cw',
  mirrorV: 'mirror_v',
  mirrorH: 'mirror_h',
  group: 'group',
  ungroup: 'group_ungroup',
  symbolEditor: 'libedit',
  symbolBrowser: 'library_browser',
  footprintEditor: 'module_editor',
  annotate: 'annotate',
  erc: 'erc',
  simulator: 'simulator',
  assignFootprints: 'icon_cvpcb_24',
  editSymbolFields: 'spreadsheet',
  bom: 'post_bom',
  // left toolbar
  toggleGrid: 'grid',
  toggleGridOverrides: 'grid_override',
  unitsInches: 'unit_inch',
  unitsMils: 'unit_mil',
  unitsMm: 'unit_mm',
  crosshairSmall: 'cursor_shape',
  crosshairFull: 'cursor_fullscreen',
  toggleHiddenPins: 'hidden_pin',
  lineModeFree: 'lines_any',
  lineMode90: 'lines90',
  lineMode45: 'hv45mode',
  annotateAuto: 'annotate',
  showHierarchy: 'hierarchy_nav',
  showProperties: 'tools',
  // right toolbar
  select: 'cursor',
  highlightNet: 'net_highlight_schematic',
  placeSymbol: 'add_component',
  placePower: 'add_power',
  drawWire: 'add_line',
  drawBus: 'add_bus',
  busEntry: 'add_line2bus',
  noConnect: 'noconn',
  junction: 'add_junction',
  placeLabel: 'add_label',
  placeGlobalLabel: 'add_glabel',
  placeHierLabel: 'add_hierarchical_label',
  drawSheet: 'add_hierarchical_subsheet',
  sheetPin: 'add_hierar_pin',
  placeText: 'text',
  textBox: 'add_textbox',
  table: 'table',
  rectangle: 'add_rectangle',
  circle: 'add_circle',
  arc: 'add_arc',
  bezier: 'add_bezier',
  lines: 'add_graphical_segments',
  image: 'image',
  delete: 'delete_cursor',
  // symbol editor (icons per SCH_ACTIONS/ACTIONS .Icon() used by toolbars_symbol_editor.cpp)
  newSymbol: 'new_component',
  symbolProperties: 'part_properties',
  pinTable: 'pin_table',
  showDatasheet: 'datasheet',
  checkSymbol: 'erc',
  morganStd: 'morgan1',
  morganAlt: 'morgan2',
  syncedPins: 'pin2pin',
  addSymbolToSchematic: 'add_symbol_to_schematic',
  showElectricalTypes: 'pin_show_etype',
  showHiddenFields: 'text_sketch',
  showLibraryTree: 'search_tree',
  placePin: 'pin',
  placeAnchor: 'anchor',
  polygon: 'add_graphical_polygon',
  newLibrary: 'new_library',
  addLibrary: 'add_library',
  saveAs: 'save_as',
  revert: 'restore_from_file',
  importSymbol: 'import',
  exportSymbol: 'export_file',
  cut: 'cut',
  copy: 'copy',
  library: 'library',
  editWithLibEdit: 'edit_cmp_symb_links',
  preferences: 'preference',
  // footprint editor (icons per PCB_ACTIONS/ACTIONS .Icon() in toolbars_footprint_editor.cpp).
  // KiCad's footprint-specific bitmaps aren't all vendored yet, so these reuse the
  // closest available SVGs (a footprint glyph, sketch/props icons, import/export…).
  newFootprint: 'module',
  createFootprint: 'new_generic',
  footprintProperties: 'part_properties',
  padTable: 'spreadsheet',
  defaultPadProperties: 'pad_sketch',
  checkFootprint: 'erc',
  placePad: 'pad_sketch',
  loadFpFromBoard: 'import',
  saveFpToBoard: 'export_file',
  setAnchor: 'anchor',
  graphicsOutlines: 'pad_sketch',
  textOutlines: 'text_sketch',
};

/** KiCad icon URL for a toolbar tool id, or undefined if none is mapped. */
export function toolbarIconUrl(id: string): string | undefined {
  const name = BITMAP[id];
  return name ? URLS[`../assets/toolbar/${name}.svg`] : undefined;
}
